config/routes.rb
SampleApp::Application.routes.draw do
 
  root  'sessions#new'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :clients
  resources :requests

  match '/home', to: 'static_pages#home', via:'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  

end

app/models/client.rb
class Client < ActiveRecord::Base

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	VALID_IDNUMBER_REGEX =  /\A\d{10}/

	validates :idnumber, presence: true, uniqueness: true, format: { with: VALID_IDNUMBER_REGEX }
	validates :name, presence: true
	validates :lastname, presence: true
	validates :age, presence: true	
	validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	before_save { self.email = email.downcase }

	has_many :requests, foreign_key: "requester_id"
	has_many :requests_against, foreign_key: "requested_id", class_name: "Request"

	def name_with_initial
    	"#{name}.#{lastname}"
  	end



end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :requested, class_name: "Client"
 	belongs_to :requester, class_name: "Client"
 	validates :requester_id, presence: true
    validates :requested_id, presence: true
    validates :details, presence: true
    has_attached_file :appendices, :url => "/files/:id/appendices.pdf"
    has_attached_file :proofs, :url => "/files/:id/proofs.pdf"
    
    validates_attachment_content_type :proofs, :content_type => 'application/pdf'
    validates_attachment_content_type :appendices, :content_type => 'application/pdf'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.paginate(page: params[:page], per_page: 10)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:success] = "Cliente guardado!"
      redirect_to @client
    else
      render 'new'
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to clients_url
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @client = Client.find(params[:id])
    @requests = Request.find_by(requester_id: @client.id)
  end

  def requesting?(other_client)
    requests.find_by(requested_id: other_user.id)
  end

  
  private

    def client_params
      params.require(:client).permit(:name, :lastname, :email, :age,
                                   :idnumber)
    end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	def new

		@request = Request.new		
		
	end

	def create

		@request = Request.new(request_params)
    	if @request.save    		
      		flash[:success] = "Solicitud guardada!"
     		redirect_to @request
    	else
      		render 'new'
    	end

	end

	def show

    	@request = Request.find(params[:id]) 

	end

	def destroy

		Request.find(params[:id]).destroy
    	flash[:success] = "Solicitud eliminada satisfactoriamente."
    	redirect_to requests_url
		
	end

	
	def index
		
    	@requests = Request.paginate(page: params[:page], per_page: 10)  
		
	end


	private

		def request_params
	      params.require(:request).permit(:requester_id, :requested_id, :details, :pleas, :appendices, :proofs)
	    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to '/home'
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end

  end

   def destroy

    sign_out
    redirect_to root_url
    
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def help
  end

  def about
  	
  end

  def contact
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :new]

  def new

  	@user = User.new

  end

  def show

    @user = User.find(params[:id])

  end

  def index

    @users = User.paginate(page: params[:page])

  end

  def destroy

    User.find(params[:id]).destroy
    flash[:success] = "Usuario eliminado satisfactoriamente."
    redirect_to users_url

  end

 

  def create

    @user = User.new(user_params)
    if @user.save 
      
      flash[:success] = "Usuario creado!"
      redirect_to users_url
      
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update

    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end

  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Sistema de Registro de Solicitudes de Conciliación"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end



  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 150 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/clients/_client.html.erb
<li>
	<span>

  <%= gravatar_for client, size: 52 %>
  <%= link_to client.name+" "+client.lastname, client %> |
  <%= client.idnumber %>
  <br>
  <span class="label label-warning"><%= client.email %></span>
  
</span>


 
    <span style="float: right"> <%= link_to "Eliminar", client, method: :delete,
                                  data: { confirm: "Confirmar la eliminación del cliente" } %></span>
  
</li>

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<% provide(:title, "Editar cliente") %>
<h1>Actualizar cliente</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@cliente) do |f| %>
      <%= render 'shared/error_messages_clientes' %>

      <%= f.label :idnumber %>
      <%= f.text_field :idnumber %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname %>

      <%= f.label :age %>
      <%= f.number_field :age %>

      <%= f.label :email  %>
      <%= f.text_field :email %>
      <%= f.submit "Guardar", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @client %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/clients/index.html.erb
<% provide(:title, 'Clientes') %>
<h1>Clientes registrados</h1>

<%= link_to "Crear cliente", new_client_path, class: "btn btn-large btn-primary"  %>

<%= will_paginate %>

<ul class="users">
  <%= render @clients %>
</ul>

<%= will_paginate %>

app/views/clients/new.html.erb
<% provide(:title, 'Nuevo cliente') %>
<h1>Nuevo cliente</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@client) do |f| %>
     <%= render 'shared/error_messages_clients' %>

      <%= f.label :idnumber, 'Identificación' %>
      <%= f.text_field :idnumber %>

      <%= f.label :name, 'Nombre' %>
      <%= f.text_field :name %>

      <%= f.label :lastname, 'Apellido' %>
      <%= f.text_field :lastname %>

      <%= f.label :age, 'Edad' %>
      <%= f.number_field :age %>

      <%= f.label :email, 'Correo'  %>
      <%= f.text_field :email %>

      <%= f.label :estrato, 'Estrato'  %>
      <%= f.text_field :estrato %>

      <%= f.label :phone_number, 'Teléfono'  %>
      <%= f.text_field :phone_number %>

      <%= f.label :occupation, 'Ocupación'  %>
      <%= f.text_field :occupation %>

      <%= f.label :address, 'Dirección'  %>
      <%= f.text_field :address %>


      <br>
      <br>

      <%= f.submit "Crear cliente", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/clients/show.html.erb
<% provide(:title, @client.name) %>
<h1>Información del cliente</h1>
<br>
<br>

<div class="row">
  <aside class="span8">
    <section>
      <h1>
        <%= gravatar_for @client %>
        <br>
        <%= @client.name+" "+@client.lastname %>
      </h1>
      <em><%= @client.email %><em>
      <br>
      <br>
      <span class="label label-warning">Usuario</span>
  	</section>
  	<br>
  	<br>

    
  </aside>
  <aside class="span6" >
  	<section>
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Identificación</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.idnumber %>
  			</div>
		</div>
  	</section>
  	<section>
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Edad</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.age %>
  			</div>
		</div>
  	</section>
  	<section>
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Teléfono</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.phone_number %>
  			</div>
		</div>
  	</section>
  	
  </aside>
   <aside class="span6" >
  	<section>
  		<div>
  			<div class="panel-heading">
    			<h2 class="panel-title">Dirección</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.address %>
  			</div>
		</div>
  	</section>
  	<section>
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Ocupación</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.occupation %>
  			</div>
		</div>
  	</section>
  	<section>
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Estrato</h2>
  			</div>
  			<div class="panel-body">
    			<%= @client.estrato %>
  			</div>
		</div>
  	</section>
  	
  </aside>
</div>
<br>
<br>
<br>
<br>
<div class="span5" style="text-align:center" >
  
  <table class="table-bordered">
    <caption><strong>Solicitudes generadas</strong></caption>
    <tr>
      <th>
      Solicitud Nº
      </th>
      <th>
       Solicitada a
     </th>
     <th>
        Resumen
      </th>      
    </tr>   
    <% if @client.requests.any? %>   
      <% @client.requests.each do |r| %>
      <tr>
        <td>
          <%= link_to r.id, request_path(r) %>
        </td>
        <td>
          <%= link_to "#{r.requested.name} #{r.requested.lastname}", client_path(r.requested) %>
        </td>
        <td>
          <%= r.details %>
        </td>
          
      </tr>
        
      <% end %>
    <% else %>
    <tr>
      <td colspan=3>
        <h2>Ninguna</h2>
        
      </td>
    </tr>
    <% end %>

  </table>


</div>

<div class="span5" style="text-align:center;display:inline-block">
  
  <table class="table-bordered">
    <caption><strong>Solicitudes en contra</strong></caption>
    <tr>
      <th>
      Solicitud Nº
      </th>
      <th>
       Solicitado por
     </th>
     <th>
        Resumen
      </th>      
    </tr>
    <% if @client.requests_against.any? %>   
      <% @client.requests_against.each do |r| %>
      <tr>
        <td>
          <%= link_to r.id, request_path(r) %>
        </td>
        <td>
          <%= link_to "#{r.requester.name} #{r.requester.lastname}", client_path(r.requester) %>
        </td>
        <td>
          <%= r.details %>
        </td>
          
      </tr>
        
      <% end %>
    <% else %>
    <tr>
      <td colspan=3>
        <h2>Ninguna</h2>
        
      </td>
    </tr>
    <% end %>

  </table>
  


</div>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">counseling_app</a>
    by Alejandro Guerrero
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de...",   about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Sistema de Conciliaciones", '/home', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Inicio", '/home' %></li>
          
          <% if signed_in? %>
            <li><%= link_to "Clientes", clients_path %></li>
            <li><%= link_to "Solicitudes", requests_path %></li>

            <% if current_user.admin? %>
              <li><%= link_to "Usuarios", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Opciones", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Salir", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Ingresar", signin_path %></li>
          <% end %>
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' if controller_name != 'sessions'%>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <% debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/requests/_request.html.erb
<li>
	<span> Solicitud Nº <%= request.id %> | <%= link_to request.details, request %> </span>
	<table class="table table-striped">
		<tr>
			<th>
				Fecha 
			</th>
			<th>
				Solicitud Nº
			</th>
			<th>
				ID del solicitante
			</th>
			<th>
				Nombre del solicitante
			</th>
			<th>
				ID del solicitado
			</th>
			<th>
				Nombre del solicitado
			</th>
			<th>
				Resumen
			</th>

		</tr>

 
	</table>
  
  

 
    
  
</li>

app/views/requests/index.html.erb
<% provide(:title, 'Solicitudes') %>
<h1>Solicitudes registradas</h1>

<%= link_to "Crear solicitud", new_request_path, class: "btn btn-large btn-primary" %>

<hr>


<table class="table table-striped">
		<tr>
			<th>
				Fecha 
			</th>
			<th>
				Solicitud Nº
			</th>
			<th>
				ID del solicitante
			</th>
			<th>
				Nombre del solicitante
			</th>
			<th>
				ID del solicitado
			</th>
			<th>
				Nombre del solicitado
			</th>
			<th>
				Resumen
			</th>

		</tr>
		<%= will_paginate %>
		<% @requests.each do |request| %>
		




		
		<tr>
			<td>
				<%= request.created_at.strftime("%d/%m/%Y") %>
			</td>
			<td>
				<%= link_to request.id, request_path(request) %>
			</td>
			<td>
				<%= request.requester.idnumber %>
			</td>
			<td>
				<%= link_to "#{request.requester.name} #{request.requester.lastname}", client_path(request.requester) %>
			</td>
			<td>
				<%= request.requested.idnumber %>
			</td>
			<td>
				<%= link_to "#{request.requested.name} #{request.requested.lastname}", client_path(request.requested) %>
			</td>
			<td>
				<%= request.details %>
			</td>
		</tr>

		
		<% end %>


 
	</table>
	<%= will_paginate %>

app/views/requests/new.html.erb
<% provide(:title, 'Nueva solicitud') %>
<h1>Nueva solicitud</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @request, :url => requests_path, :html => { :multipart => true } do |f| %>
     <%= render 'shared/error_messages_requests' %>

      <%= f.label :requester_id, 'Solicitante' %>
      <%= f.collection_select :requester_id, Client.order(:lastname),:id,:name_with_initial, prompt: "Seleccione un cliente..." %>


      <%= f.label :requested_id, 'Solicitado' %>
      <%= f.collection_select :requested_id, Client.order(:id),:id,:name_with_initial, prompt: "Seleccione un cliente..." %>

      <%= f.label :details, 'Detalles' %>
      <%= f.text_area :details %>

      <%= f.label :pleas, 'Peticiones' %>
      <%= f.text_area :pleas %>

      <%= f.label :appendices, 'Anexos' %>
      <%= f.file_field :appendices %>

      <%= f.label :proofs, 'Pruebas' %>
      <%= f.file_field :proofs %>



     
      <%= f.submit "Crear solicitud", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<% provide(:title, 'Solicitud Nº '+@request.id.to_s) %>

<h1>Información de la Solicitud</h1>

<div class="container" style="padding-top:40px">
	<div> 

		<h3> Solicitud Nº <%= @request.id %> </h3>
		<div style="text-align:right"><%= @request.created_at.strftime("%d/%m/%Y") %></div>
		<hr>
		<br>
		

		<div class="span3 offset3 panel panel-success">
			<div class="panel-heading">
				<h2 class="panel-title">Solicitante </h2>
			</div>
			<div class="panel-body" style="text-align:center">
				<h3 style="text-align:center"><%= link_to "#{@request.requester.name} #{@request.requester.lastname}", client_path(@request.requester)%></h3>
				
				<span><%= @request.requester.idnumber %></span>
			</div>
		</div>
		
		<div class="span3 panel panel-warning">
			<div class="panel-heading">
				<h2 class="panel-title">Solicitado</h2>
			</div>
			<div class="panel-body" style="text-align:center">
				<h3 style="text-align:center"><%= link_to "#{@request.requested.name} #{@request.requested.lastname}", client_path(@request.requested) %></h3>
				<span><%= @request.requester.idnumber %></span>
			</div>		

		</div>
		

	</div>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<hr>
	<br>

	

	<dl class="dl-horizontal">

	  		<dt>Hechos:</dt>
	  		<dd>
	  			<div>
	  				<textarea disabled rows = "10" readonly style="resize:none;owerflow-y:scroll"><%= @request.details %></textarea>
	  			</div>
	  			
	  		</dd>
	</dl>

	<br>

	<dl class="dl-horizontal">

	  		<dt>Peticiones:</dt>
	  		<dd>
	  			<div>
	  				<textarea disabled rows = "10" readonly style="resize:none;owerflow-y:scroll"><%= @request.pleas %></textarea>
	  			</div>
	  			
	  		</dd>
	</dl>

	<hr>

	<div class="span3 offset3">
		<% if @request.appendices.url != "/appendices/original/missing.png" %>
			<h3><%= link_to "Anexos", @request.appendices.url(:original,false) %></h3>
		<% else %>
			<h3>No se agregaron anexos</h3>
		<% end %>
	</div>

	<div class="span3">
		<% if @request.appendices.url != "/appendices/original/missing.png" %>
			<h3><%= link_to "Pruebas", @request.proofs.url(:original,false) %></h3>
		<% else %>
			<h3>No se agregaron pruebas</h3>
		<% end %>
	</div>
	
	

	
	
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_clients.html.erb
<% if @client.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@client.errors.count, "error") %>.
    </div>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_requests.html.erb
<% if @request.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@request.errors.count, "error") %>.
    </div>
    <ul>
    <% @request.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1>Quienes somos?</h1>
<p>
 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contacto') %>
<h1>Contáctanos</h1>
<p>
  
</p>

app/views/static_pages/help.html.erb
<<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  
</p>

app/views/static_pages/home.html.erb
<br>
<div class="center hero-unit">
  <h1>Estado del sistema</h1>

  <h2>
    Aquí se muestra un resumen de los datos guardados hasta el momento en el sistema.
  </h2>


</div>
<br>
<br>
<br>
<br>


<aside class="span3 offset1" >
  	  	<section style="border: 1px solid">
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Usuarios registrados</h2>
  			</div>
  			<div class="panel-body">
    			<span style="text-align:center"><h3 stlye="align:center"><%= User.count %><h3></span>
  			</div>
		</div>
  	</section>
  </aside>

   <aside class="span3">
  	  	<section style="border: 1px solid">
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Clientes registrados</h2>
  			</div>
  			<div class="panel-body">
    			<span style="text-align:center"><h3 stlye="align:center"><%= Client.count %><h3></span>
  			</div>
		</div>
  	</section>
  	
  </aside>

   <aside class="span3">
  	  	<section style="border: 1px solid">
  		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h2 class="panel-title">Solicitudes generadas</h2>
  			</div>
  			<div class="panel-body">
    			<span style="text-align:center"><h3 stlye="align:center"><%= Request.count %><h3></span>
  			</div>
		</div>
  	</section>
  </aside>


<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/users/_user.html.erb
<li>
	<span>
		<%= gravatar_for user, size: 52 %>
  		<%= link_to user.email, user %>
	</span>
	<span style="float:right">
		<% if current_user.admin? && !current_user?(user) %>
    	 <%= link_to "Eliminar", user, method: :delete,
                                  data: { confirm: "Confirme la elminación del usuario" } %>
  		<% end %>
	</span>
  
  
</li>

app/views/users/index.html.erb
<% provide(:title, 'Usuarios') %>
<h1>Usuarios registrados</h1>

<%= link_to "Crear usuario", new_user_path, class: "btn btn-large btn-primary"  %>
<br>
<br>
<br>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>